"""add iban

Revision ID: bc6c672cfd3f
Revises: 3be1a331dc8c
Create Date: 2022-08-05 22:31:54.091432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6c672cfd3f'
down_revision = '3be1a331dc8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('iban', sa.String(length=22), nullable=False))
    op.add_column('approvers', sa.Column('iban', sa.String(length=22), nullable=False))
    op.add_column('complainers', sa.Column('iban', sa.String(length=22), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complainers', 'iban')
    op.drop_column('approvers', 'iban')
    op.drop_column('admins', 'iban')
    # ### end Alembic commands ###
