name: Python complaint system
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies and test
      env:
        DB_USER: “{your user}"
        DB_PASSWORD: “{your password}”
        DB_PORT: '5432'
        DB_NAME: 'test_db'
        SECRET_KEY: ""
        AWS_ACCESS_KEY: ""
        AWS_SECRET: ""
        AWS_BUCKET: ""
        AWS_REGION: ""
        WISE_TOKEN: ""
        WISE_URL: "" 
        POSTGRES_PASSWORD: admin
        POSTGRES_USER: admin
        POSTGRES_DB: test_db
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        export PGPASSWORD="admin"
        pytest
